defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: news/:title
exclude: 
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md
  - publications/citations/
